In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

In [2]:
def multiclassScore(y: pd.Series, y_pred: pd.Series,normalize :bool = False) -> float:
    if (y.astype(int).apply(lambda x: x in [0,1,2,3,4]).all() == False) or (y_pred.astype(int).apply(lambda x: x in [0,1,2,3,4]).all() == False) :
        raise ValueError('y and y_pred are only allowed to contain the elements 0,1,2,3,4')


    behaviourY = np.where(y>0,1,0) #1 is buying
    behaviourPredY = np.where(y_pred>0,1,0)
    correctBehaviour = np.sum(behaviourY == behaviourPredY)

    correctPredictionsWeek = np.sum((y == y_pred) & (y > 0))

    score = (correctBehaviour-correctPredictionsWeek)*1+correctPredictionsWeek*3

    if normalize == True:
        maxScore = np.sum((y>0)*3 + (y==0)*1)
        return(score/maxScore)
    else:
        return(score)


# Import datasets

In [7]:
train_set = pd.read_csv('train_all_features_multiclass_heuristics_updated.csv', sep=';', decimal=',')
test_set = pd.read_csv('test_all_features_multiclass_heuristics_updated.csv', sep = ";", decimal = ",")
train_set

userID  itemID  prediction  last14d  cumsum  similar.0COrderSumIncl  \
0       45301     461           2        0       3                      19   
1        5898     461           0        0       2                      15   
2        7168     461           0        0       4                      18   
3        3757     461           0        0       2                      42   
4       41695     461           2        0       2                      31   
...       ...     ...         ...      ...     ...                     ...   
56707   44010   13756           0        0       2                       4   
56708   23835   20278           0        0       2                       2   
56709   15195    7751           0        0       6                       6   
56710   19832   10535           0        0       2                       9   
56711   16655    8919           4        2       4                       4   

       similar.0COrderCountIncl  similar.0COrderSumExcl  \
0                            15                      16   
1                            12                      13   
2                            14                      14   
3                            33                      40   
4                            14                      29   
...                         ...                     ...   
56707                         4                       2   
56708                         2                       0   
56709                         3                       0   
56710                         9                       7   
56711                         2                       0   

       similar.0COrderCountExcl  avg_time_orders  ...  IT_PCA_comp2  \
0                            12             83.5  ...     -0.181485   
1                            10            102.0  ...     -0.181485   
2                            12            147.0  ...     -0.181485   
3                            31             71.0  ...     -0.181485   
4                            12             62.0  ...     -0.181485   
...                         ...              ...  ...           ...   
56707                         2              2.0  ...      0.242416   
56708                         0             17.0  ...      0.165381   
56709                         0             55.0  ...     -0.529354   
56710                         7             79.0  ...     -0.302991   
56711                         0             26.0  ...      0.313937   

       IT_PCA_comp3  IT_PCA_comp4  IT_PCA_comp5  IT_PCA_NA  UI_againmean2  \
0         -0.004367     -0.074567     -0.004844      False              0   
1         -0.004367     -0.074567     -0.004844      False              0   
2         -0.004367     -0.074567     -0.004844      False              0   
3         -0.004367     -0.074567     -0.004844      False              1   
4         -0.004367     -0.074567     -0.004844      False              0   
...             ...           ...           ...        ...            ...   
56707     -0.218993     -0.469199      0.016486      False              0   
56708     -0.140319      0.036076      0.151156      False              0   
56709      0.270354     -0.051241     -0.026983      False              2   
56710      0.203427      0.079796      0.029775      False              0   
56711     -0.436930     -0.077091      0.198414      False              2   

       UI_distmean2  Unnamed..0 useractivity itemincidence  
0                 8       29195     0.363636      0.783784  
1                 7        3844     0.375000      0.783784  
2                12        4622     0.333333      0.783784  
3                 0        2475     0.454545      0.783784  
4                 6       26897     0.444444      0.783784  
...             ...         ...          ...           ...  
56707            -3       28367     1.000000      1.000000  
56708            -4       15363     0.375000      0.200000  
56709             0        9802   

In [8]:
train = train_set[['userID', 'itemID', 'prediction']].copy()
test = test_set[['userID', 'itemID', 'prediction']].copy()

In [9]:
u_features = pd.read_csv('U_FEAT_till_3_1.csv', index_col=0)
i_features = pd.read_csv('item_features_TIMO.csv', index_col=0, sep=',')
ui_train_features = pd.read_csv('train_allFeatures.csv', index_col=0, sep='|')
ui_test_features = pd.read_csv('test_allFeatures.csv', index_col=0, sep='|')
i_features

IT_performance_change_whole_branch_cb  itemID  \
0                                       0.0       1   
1                       0.05454545454545454       6   
2                       0.07191780821917808       8   
3                      -0.10679611650485436       9   
4                       0.42857142857142855      11   
...                                     ...     ...   
12297                                  mean   32764   
12298                 0.0036377560788818687   32766   
12299                 -0.060291060291060294   32768   
12300                  -0.13043478260869565   32769   
12301                                   0.0   32770   

      IT_performance_change_whole_branch_fb  \
0                       0.00463678516228748   
1                      -0.07226107226107226   
2                      0.037037037037037035   
3                      -0.13513513513513514   
4                                       0.2   
...                                     ...   
12297                                  mean   
12298                   -0.3333333333333333   
12299                   -0.3617021276595745   
12300                  -0.08847184986595175   
12301                  -0.14285714285714285   

      IT_performance_in_branch_fb_change IT_performance_in_branch_cb_change  \
0                  -0.020663072006324057                               -1.0   
1                   0.026129962020457018                 0.0747764799996038   
2                    0.10754221087554419               0.014345587108794071   
3                                    0.0               -0.03339757266082727   
4                                   -1.0                               -1.0   
...                                  ...                                ...   
12297                               mean                               mean   
12298                -0.6428571428571429             -0.0020300012604868643   
12299                 0.2790816326530613               0.006854993082102842   
12300                0.03511235779319133                                0.0   
12301               -0.27976190476190477                               -1.0   

      IT_performance_in_branch_fb IT_performance_in_branch_cb  \
0                             0.0                         0.0   
1             0.09893312516263336          0.5897435897435898   
2             0.23737373737373738         0.04337393872277593   
3                             1.0          0.3576923076923077   
4                             0.0                         0.0   
...                           ...                         ...   
12297                        mean                        mean   
12298                         0.0                         0.0   
12299          0.7833333333333333        0.048420698924731186   
12300         0.12043516800659657                         1.0   
12301                         0.0                         0.0   

       IT_rebought_rate_ft1  IT_rebought_rate_ft2  IT_rebought_rate_ft3  ...  \
0                  0.285652              0.287673              0.277664  ...   
1                  0.291240              0.287673              0.400000  ...   
2                  0.285652              0.287673              0.352814  ...   
3                  0.285652              0.269808              0.262343  ...   
4                  0.291240              0.269808              0.230769  ...   
...                     ...                   ...                   ...  ...   
12297              0.285652              0.255614              0.166667  ...   
12298              0.285652              0.269808              0.288660  ...   
12299              0.291240              0.287673              0.343590  ...   
12300              0.260256              0.287673              0.267231  ...   
12301              0.291240              0.272936              0.279779  ...   

       IT_boughts_total  IT_boughts_last6w  IT_prct_last6w  IT_not_avaible  \
0          

In [10]:
ui_features = pd.concat([ui_train_features, ui_test_features], axis=0)
ui_features

userID  itemID  cumsum  last7d  last14d  last21d  last28d  \
0        1199     637       5     0.0      0.0      0.0      0.0   
1       21557    3520       2     0.0      0.0      0.0      0.0   
2       23387    1633       2     0.0      0.0      0.0      0.0   
3       32069   29311       5     0.0      0.0      0.0      2.0   
4       30359   11124       2     0.0      0.0      0.0      0.0   
...       ...     ...     ...     ...      ...      ...      ...   
27529    2176    9773       2     0.0      0.0      0.0      0.0   
27530   20041   19824       4     0.0      0.0      0.0      0.0   
27531   39920   18714       4     0.0      0.0      0.0      0.0   
27532    5127    1299       3     1.0      1.0      1.0      1.0   
27533   29975   11454       3     0.0      0.0      0.0      0.0   

       similar>0COrderSumIncl  similar>0COrderCountIncl  \
0                           5                         2   
1                           3                         3   
2                           2                         2   
3                           9                         7   
4                          11                        11   
...                       ...                       ...   
27529                       5                         5   
27530                       4                         4   
27531                       4                         2   
27532                       6                         6   
27533                      19                        17   

       similar>0COrderSumExcl  similar>0COrderCountExcl  \
0                           0                         0   
1                           1                         1   
2                           0                         0   
3                           4                         4   
4                           9                         9   
...                       ...                       ...   
27529                       3                         3   
27530                       0                         0   
27531                       0                         0   
27532                       3                         3   
27533                      16                        15   

       sameBrandOrderSumIncl  sameBrandOrderCountIncl  sameBrandOrderSumExcl  \
0                          6                        3                      1   
1                          3                        3                      1   
2                          2                        2                      0   
3                          5                        3                      0   
4                          2                        2                      0   
...                      ...                      ...                    ...   
27529                      4                        4                      2   
27530                      4                        4                      0   
27531                      4                        2                      0   
27532                      5                        5                      2   
27533                      3                        2                      0   

       sameBrandOrderCountExcl  order  avg_time_orders  day_first_purchase  \
0                            1      3       126.000000                  14   
1                            1      1        83.000000                  72   
2                            0      1       124.000000                  31   
3                            0      2        28.000000                 135   
4                            0      1        10.000000                 119   
...                        ...    ...              ...                 ...   
27529                        2      1        42.000000                 138   
27530                        0      1        53.333333                  25   
27531                        0      2       159.000000                  23   
27532                        2 

## Selecting only some important features

In [11]:
#item_feat = i_features[['itemID','IT_boughts_total','IT_boughts_last6w', 'IT_avg_time_btw_boughts']].copy()
ui_feat = ui_features.drop(columns = ['last7d', 'last14d', 'last21d', 'last28d', 'order'])
u_feat = u_features.drop(columns = ['u_EF'])
ui_feat

userID  itemID  cumsum  similar>0COrderSumIncl  \
0        1199     637       5                       5   
1       21557    3520       2                       3   
2       23387    1633       2                       2   
3       32069   29311       5                       9   
4       30359   11124       2                      11   
...       ...     ...     ...                     ...   
27529    2176    9773       2                       5   
27530   20041   19824       4                       4   
27531   39920   18714       4                       4   
27532    5127    1299       3                       6   
27533   29975   11454       3                      19   

       similar>0COrderCountIncl  similar>0COrderSumExcl  \
0                             2                       0   
1                             3                       1   
2                             2                       0   
3                             7                       4   
4                            11                       9   
...                         ...                     ...   
27529                         5                       3   
27530                         4                       0   
27531                         2                       0   
27532                         6                       3   
27533                        17                      16   

       similar>0COrderCountExcl  sameBrandOrderSumIncl  \
0                             0                      6   
1                             1                      3   
2                             0                      2   
3                             4                      5   
4                             9                      2   
...                         ...                    ...   
27529                         3                      4   
27530                         0                      4   
27531                         0                      4   
27532                         3                      5   
27533                        15                      3   

       sameBrandOrderCountIncl  sameBrandOrderSumExcl  \
0                            3                      1   
1                            3                      1   
2                            2                      0   
3                            3                      0   
4                            2                      0   
...                        ...                    ...   
27529                        4                      2   
27530                        4                      0   
27531                        2                      0   
27532                        5                      2   
27533                        2                      0   

       sameBrandOrderCountExcl  avg_time_orders  day_first_purchase  \
0                            1       126.000000                  14   
1                            1        83.000000                  72   
2                            0       124.000000                  31   
3                            0        28.000000                 135   
4                            0        10.000000                 119   
...                        ...              ...                 ...   
27529                        2        42.000000                 138   
27530                        0        53.333333                  25   
27531                        0       159.000000                  23   
27532                        2        47.500000                 118   
27533                        0        58.000000                  62   

       day_last_purchase  usage_time_items  
0                    140         42.000000  
1                    155         83.000000  
2                    155        124.000000  
3                    191         21.250000  
4                    129         10.000000  
...                  ...               ...  
27529                180         42.000000  
27530             

In [12]:
X_train = (train.merge(ui_feat, how='left', on=['userID', 'itemID'])).merge(u_feat, how='left', on='userID')
X_test = (test.merge(ui_feat, how='left', on=['userID', 'itemID'])).merge(u_feat, how='left', on='userID')

In [13]:
X_test

userID  itemID  prediction  cumsum  similar>0COrderSumIncl  \
0       27630   29657           0      11                      61   
1        4031   29657           0      12                      16   
2       33675   29657           0       5                       5   
3        1579   29657           0      26                      30   
4       43716   29657           0       6                      27   
...       ...     ...         ...     ...                     ...   
24322   26426    2929           1       4                       4   
24323   32256    2924           0       2                       9   
24324   44054   31153           0       8                       8   
24325   30371    8206           0       2                       2   
24326   41265    6143           0       4                       4   

       similar>0COrderCountIncl  similar>0COrderSumExcl  \
0                            23                      50   
1                             6                       4   
2                             3                       0   
3                             8                       4   
4                            17                      21   
...                         ...                     ...   
24322                         2                       0   
24323                         9                       7   
24324                         4                       0   
24325                         2                       0   
24326                         2                       0   

       similar>0COrderCountExcl  sameBrandOrderSumIncl  \
0                            19                     20   
1                             2                     12   
2                             0                      8   
3                             3                     26   
4                            15                      6   
...                         ...                    ...   
24322                         0                      4   
24323                         7                      4   
24324                         0                      8   
24325                         0                      2   
24326                         0                      4   

       sameBrandOrderCountIncl  ...  day_first_purchase  day_last_purchase  \
0                            7  ...                  28                160   
1                            4  ...                  27                192   
2                            6  ...                  78                189   
3                            5  ...                  31                186   
4                            2  ...                  74                151   
...                        ...  ...                 ...                ...   
24322                        2  ...                  21                153   
24323                        4  ...                  83                149   
24324                        4  ...                   4                200   
24325                        2  ...                   5                140   
24326                        2  ...                  61                178   

       usage_time_items  u_avg_orders  u_avg_period  u_first_bought  \
0             13.833333          2.18         13.29               1   
1             16.138889          1.71         33.00              27   
2             27.750000          1.78         19.86              78   
3              7.475000          2.75         34.60              31   
4             25.666667          1.52         19.70              19   
...                 ...           ...           ...             ...   
24322         66.000000          1.29         22.00              21   
24323         66.000000          1.30         30.00              51   
24324         32.666667          1.62         32.67               4   
24325        135.000000          1.79         27.86               5   
24326         39.000000          1.26         20.75   

## Random oversampling

In [14]:
amount_0 = X_train[X_train['prediction'] == 0].shape[0]
amount_1 = X_train[X_train['prediction'] == 1].shape[0]
amount_2 = X_train[X_train['prediction'] == 2].shape[0]
amount_3 = X_train[X_train['prediction'] == 3].shape[0]
amount_4 = X_train[X_train['prediction'] == 4].shape[0]

unlike_0 = amount_1 + amount_2 + amount_3 + amount_4

ratio1 = amount_1 / unlike_0
ratio2 = amount_2 / unlike_0
ratio3 = amount_3 / unlike_0
ratio4 = amount_4 / unlike_0

print(f"0: {amount_0}\t\t1: {amount_1}\t\t2: {amount_2}\t\t3: {amount_3}\t\t4: {amount_4}")

df_1_under = X_train[X_train['prediction'] == 1].sample(round(ratio1 * amount_0), replace=True)
df_2_under = X_train[X_train['prediction'] == 2].sample(round(ratio2 * amount_0), replace=True)
df_3_under = X_train[X_train['prediction'] == 3].sample(round(ratio3 * amount_0), replace=True)
df_4_under = X_train[X_train['prediction'] == 4].sample(round(ratio4 * amount_0), replace=True)

X_train_balanced_over = pd.concat([df_1_under, df_2_under, df_3_under, df_4_under, X_train[X_train['prediction'] == 0]], axis=0)

X_train_balanced_over['prediction'].value_counts()

0: 45727		1: 2609		2: 2473		3: 2836		4: 3067


0    45727
4    12767
3    11805
1    10860
2    10294
Name: prediction, dtype: int64

In [105]:
y_train = X_train_balanced_over['prediction']
y_test = X_test['prediction']
y_train

41517    1
32199    1
42768    1
23556    1
5363     1
        ..
56706    0
56707    0
56708    0
56709    0
56710    0
Name: prediction, Length: 91453, dtype: int64

## I. Random Forest Classification Model

### Training the Random Forest Classification model on the Training set

In [106]:
clf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 42)
clf.fit(X_train_balanced_over.drop('prediction', axis=1), y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=42)

### Predicting the test set result

In [107]:
y_pred = clf.predict(X_test.drop('prediction', axis=1))

### Confusion matrix and some evaluations

In [108]:
cm_forest = confusion_matrix(y_test, y_pred)
print('Confusion matrix:')
print(cm_forest)

ac_forest = accuracy_score(y_test, y_pred)
print(f"Accuracy score: {ac_forest}")

dmc_forest = multiclassScore(y_test, pd.Series(y_pred))
print(f"DMC score: {dmc_forest}")

Confusion matrix:
[[19277    94    67   116    93]
 [ 1013    67    22    15     9]
 [  990    11    57    19    17]
 [ 1029    19    18    74    13]
 [ 1176    18    20    28    65]]
Accuracy score: 0.8032227566078842
DMC score: 20275


### Applying GridSearchCV

In [109]:
params = {'criterion': ['gini', 'entropy'],
         'n_estimators': np.arange(100, 104),
         'min_samples_split': np.arange(5, 8),
         'max_depth': np.arange(16, 19)}
clf_over = GridSearchCV(estimator = clf, param_grid = params, error_score = 'raise', n_jobs=-1)
clf_over.fit(X_train_balanced_over.drop('prediction', axis=1), y_train)
clf_over.best_params_

{'criterion': 'entropy',
 'max_depth': 18,
 'min_samples_split': 5,
 'n_estimators': 101}

In [111]:
y_pred_cv = clf_over.predict(X_test.drop('prediction', axis=1))

In [112]:
cm_cv = confusion_matrix(y_test, y_pred_cv)
print('Confusion matrix:')
print(cm_cv)

ac_cv = accuracy_score(y_test, y_pred_cv)
print(f"Accuracy score: {ac_cv}")

dmc_cv = multiclassScore(y_test, pd.Series(y_pred_cv))
print(f"DMC score: {dmc_cv}")

Confusion matrix:
[[19499    38    20    48    42]
 [ 1037    52     7    20    10]
 [ 1003     9    43    19    20]
 [ 1049    13     8    71    12]
 [ 1192    14    12    26    63]]
Accuracy score: 0.8109507954125046
DMC score: 20356


# Training model based on the background data, not heuristic data

In [17]:
train_back = pd.read_csv('train_70_backgroundTrainTestsplit.csv')
test_back = pd.read_csv('test_30_backgroundTrainTestsplit.csv')
test_back

userID  itemID  prediction
0       12727    3742         0.0
1       25360   30429         3.0
2        4725   13378         0.0
3       29897     461         0.0
4       18611    2761         0.0
...       ...     ...         ...
27529   31511   22721         0.0
27530   37307   18630         0.0
27531    5659   24716         0.0
27532    3539     110         0.0
27533   36332    6923         0.0

[27534 rows x 3 columns]

In [18]:
X_train_back = train_back.merge(ui_feat, how='left', on=['userID', 'itemID']).merge(u_feat, how='left', on='userID')
X_test_back = test_back.merge(ui_feat, how='left', on=['userID', 'itemID']).merge(u_feat, how='left', on='userID')
X_train_back

userID  itemID  prediction  cumsum  similar>0COrderSumIncl  \
0       31233   21596         0.0       2                      13   
1       22721   31702         0.0       6                      19   
2       33799   18498         0.0       3                      14   
3       35553    2394         0.0       2                       2   
4       21718   10958         0.0       2                       8   
...       ...     ...         ...     ...                     ...   
64238    2541   16303         1.0       2                       2   
64239   18879   15389         0.0       3                       3   
64240    4751   11906         0.0       5                       5   
64241   36896   28827         0.0       6                       7   
64242   15176    5375         0.0       2                      11   

       similar>0COrderCountIncl  similar>0COrderSumExcl  \
0                             7                      11   
1                            13                      13   
2                            10                      11   
3                             2                       0   
4                             8                       6   
...                         ...                     ...   
64238                         2                       0   
64239                         2                       0   
64240                         5                       0   
64241                         7                       1   
64242                         8                       9   

       similar>0COrderCountExcl  sameBrandOrderSumIncl  \
0                             5                      6   
1                            11                      8   
2                             7                      3   
3                             0                      2   
4                             6                      2   
...                         ...                    ...   
64238                         0                      2   
64239                         0                      3   
64240                         0                     18   
64241                         1                      6   
64242                         6                      3   

       sameBrandOrderCountIncl  ...  day_first_purchase  day_last_purchase  \
0                            4  ...                  72                189   
1                            4  ...                  37                179   
2                            3  ...                  14                150   
3                            2  ...                  89                194   
4                            2  ...                  22                168   
...                        ...  ...                 ...                ...   
64238                        2  ...                  78                161   
64239                        2  ...                  96                181   
64240                       18  ...                  22                210   
64241                        6  ...                   3                195   
64242                        3  ...                  86                118   

       usage_time_items  u_avg_orders  u_avg_period  u_first_bought  \
0            117.000000          1.64         36.20               8   
1             47.333333          1.76         13.92              33   
2             68.000000          1.26         20.89              14   
3            105.000000          1.19         27.33              30   
4            146.000000          1.09         18.50              22   
...                 ...           ...           ...             ...   
64238         83.000000          1.26         17.25               3   
64239         85.000000          1.22         28.00              13   
64240         47.000000          1.42         17.00               6   
64241         38.400000          1.43         16.00               3   
64242         32.000000          1.29         17.57   

### Random oversampling

In [19]:
amount_0 = X_train_back[X_train_back['prediction'] == 0].shape[0]
amount_1 = X_train_back[X_train_back['prediction'] == 1].shape[0]
amount_2 = X_train_back[X_train_back['prediction'] == 2].shape[0]
amount_3 = X_train_back[X_train_back['prediction'] == 3].shape[0]
amount_4 = X_train_back[X_train_back['prediction'] == 4].shape[0]

unlike_0 = amount_1 + amount_2 + amount_3 + amount_4

ratio1 = amount_1 / unlike_0
ratio2 = amount_2 / unlike_0
ratio3 = amount_3 / unlike_0
ratio4 = amount_4 / unlike_0

print(f"0: {amount_0}\t\t1: {amount_1}\t\t2: {amount_2}\t\t3: {amount_3}\t\t4: {amount_4}")

df_1_under = X_train_back[X_train_back['prediction'] == 1].sample(round(ratio1 * amount_0), replace=True)
df_2_under = X_train_back[X_train_back['prediction'] == 2].sample(round(ratio2 * amount_0), replace=True)
df_3_under = X_train_back[X_train_back['prediction'] == 3].sample(round(ratio3 * amount_0), replace=True)
df_4_under = X_train_back[X_train_back['prediction'] == 4].sample(round(ratio4 * amount_0), replace=True)

X_train_back_balanced_over = pd.concat([df_1_under, df_2_under, df_3_under, df_4_under, X_train_back[X_train_back['prediction'] == 0]], axis=0)

X_train_back_balanced_over['prediction'].value_counts()

0: 52883		1: 3030		2: 2677		3: 2798		4: 2855


0.0    52883
1.0    14105
4.0    13291
3.0    13025
2.0    12462
Name: prediction, dtype: int64

In [21]:
y_train_back = X_train_back_balanced_over['prediction']


In [29]:
y_test_back = X_test_back['prediction']

In [24]:
forest = RandomForestClassifier()
params = {'criterion': ['gini', 'entropy'],
         'n_estimators': np.arange(100, 104),
         'min_samples_split': np.arange(5, 8),
         'max_depth': np.arange(16, 19)}
clf = GridSearchCV(estimator = forest, param_grid = params, error_score = 'raise', n_jobs=-1)
clf.fit(X_train_back_balanced_over.drop('prediction', axis=1), y_train_back)
clf.best_params_

{'criterion': 'entropy',
 'max_depth': 18,
 'min_samples_split': 5,
 'n_estimators': 100}

In [25]:
y_pred_back = clf.predict(X_test_back.drop('prediction', axis=1))

In [30]:
cm_back = confusion_matrix(y_test_back, y_pred_back)
print('Confusion matrix:')
print(cm_back)

ac_back= accuracy_score(y_test_back, y_pred_back)
print(f"Accuracy score: {ac_back}")

dmc_back = multiclassScore(y_test_back, pd.Series(y_pred_back))
print(f"DMC score: {dmc_back}")

Confusion matrix:
[[22308   133    42    34    22]
 [ 1173   135    18     9     2]
 [ 1040    54    62     5     3]
 [ 1078    53    14    54     4]
 [ 1218    28     4     3    38]]
Accuracy score: 0.8206944141788335
DMC score: 23372


# Using model builted on background data to predict Submission file

In [80]:
submission = pd.read_csv('submission.csv', sep='|').drop('prediction', axis=1)
submission

userID  itemID
0          0   20664
1          0   28231
2         13    2690
3         15    1299
4         15   20968
...      ...     ...
9995   46118   20106
9996   46124   19677
9997   46125   12878
9998   46127    7963
9999   46130     395

[10000 rows x 2 columns]

### import feature datasets up to 31.1.2021

In [86]:
ui_31 = pd.read_csv('wholeJanUserItemFeatures.csv', sep='|')
ui_feat_31 = ui_31.drop('buysLast14d', axis=1)
ui_feat_31.rename(columns={'usageTime': 'usage_time_items'}, inplace = True)
u_31 = pd.read_csv('U_FEAT_till_31_1.csv', index_col=0)
u_feat_31 = u_31.drop(columns = ['u_EF'])
ui_feat_31

userID  itemID  similar>0COrderSumIncl  similar>0COrderCountIncl  \
0            0    1505                       2                         2   
1            0    6446                       3                         3   
2            0    9325                       6                         5   
3            0   12468                       1                         1   
4            0   12505                       2                         2   
...        ...     ...                     ...                       ...   
896421   46137   22403                       1                         1   
896422   46137   22583                       1                         1   
896423   46137   28343                       3                         2   
896424   46137   28900                       6                         4   
896425   46137   32292                       7                         5   

        similar>0COrderSumExcl  similar>0COrderCountExcl  \
0                            1                         1   
1                            1                         1   
2                            5                         4   
3                            0                         0   
4                            1                         1   
...                        ...                       ...   
896421                       0                         0   
896422                       0                         0   
896423                       2                         1   
896424                       4                         3   
896425                       5                         4   

        sameBrandOrderSumIncl  sameBrandOrderCountIncl  sameBrandOrderSumExcl  \
0                           2                        2                      1   
1                           2                        2                      0   
2                           1                        1                      0   
3                           1                        1                      0   
4                           1                        1                      0   
...                       ...                      ...                    ...   
896421                      2                        2                      1   
896422                      1                        1                      0   
896423                      1                        1                      0   
896424                      2                        1                      0   
896425                      2                        1                      0   

        sameBrandOrderCountExcl  cumsum  avg_time_orders  day_first_purchase  \
0                             1       1              0.0                  92   
1                             0       2             35.0                 193   
2                             0       1              0.0                 172   
3                             0       1              0.0                  63   
4                             0       1              0.0                  78   
...                         ...     ...              ...                 ...   
896421                        1       1              0.0                 231   
896422                        0       1              0.0                 244   
896423                        0       1              0.0                  68   
896424                        0       2              0.0                  68   
896425                        0       2              0.0                  68   

        day_last_purchase  usage_time_items  
0                      92                 0  
1                     228                35  
2                     172                 0  
3                      63                 0  
4                      78                 0  
...                   ...               ...  
896421                231                 0  
896422                244                 0  
896423                 68 

In [63]:
ui_feat_31.columns

Index(['userID', 'itemID', 'similar>0COrderSumIncl',
       'similar>0COrderCountIncl', 'similar>0COrderSumExcl',
       'similar>0COrderCountExcl', 'sameBrandOrderSumIncl',
       'sameBrandOrderCountIncl', 'sameBrandOrderSumExcl',
       'sameBrandOrderCountExcl', 'cumsum', 'avg_time_orders',
       'day_first_purchase', 'day_last_purchase', 'usage_time_items'],
      dtype='object')

In [64]:
ui_feat.columns

Index(['userID', 'itemID', 'cumsum', 'similar>0COrderSumIncl',
       'similar>0COrderCountIncl', 'similar>0COrderSumExcl',
       'similar>0COrderCountExcl', 'sameBrandOrderSumIncl',
       'sameBrandOrderCountIncl', 'sameBrandOrderSumExcl',
       'sameBrandOrderCountExcl', 'avg_time_orders', 'day_first_purchase',
       'day_last_purchase', 'usage_time_items'],
      dtype='object')

In [65]:
ui_feat

userID  itemID  cumsum  similar>0COrderSumIncl  \
0        1199     637       5                       5   
1       21557    3520       2                       3   
2       23387    1633       2                       2   
3       32069   29311       5                       9   
4       30359   11124       2                      11   
...       ...     ...     ...                     ...   
27529    2176    9773       2                       5   
27530   20041   19824       4                       4   
27531   39920   18714       4                       4   
27532    5127    1299       3                       6   
27533   29975   11454       3                      19   

       similar>0COrderCountIncl  similar>0COrderSumExcl  \
0                             2                       0   
1                             3                       1   
2                             2                       0   
3                             7                       4   
4                            11                       9   
...                         ...                     ...   
27529                         5                       3   
27530                         4                       0   
27531                         2                       0   
27532                         6                       3   
27533                        17                      16   

       similar>0COrderCountExcl  sameBrandOrderSumIncl  \
0                             0                      6   
1                             1                      3   
2                             0                      2   
3                             4                      5   
4                             9                      2   
...                         ...                    ...   
27529                         3                      4   
27530                         0                      4   
27531                         0                      4   
27532                         3                      5   
27533                        15                      3   

       sameBrandOrderCountIncl  sameBrandOrderSumExcl  \
0                            3                      1   
1                            3                      1   
2                            2                      0   
3                            3                      0   
4                            2                      0   
...                        ...                    ...   
27529                        4                      2   
27530                        4                      0   
27531                        2                      0   
27532                        5                      2   
27533                        2                      0   

       sameBrandOrderCountExcl  avg_time_orders  day_first_purchase  \
0                            1       126.000000                  14   
1                            1        83.000000                  72   
2                            0       124.000000                  31   
3                            0        28.000000                 135   
4                            0        10.000000                 119   
...                        ...              ...                 ...   
27529                        2        42.000000                 138   
27530                        0        53.333333                  25   
27531                        0       159.000000                  23   
27532                        2        47.500000                 118   
27533                        0        58.000000                  62   

       day_last_purchase  usage_time_items  
0                    140         42.000000  
1                    155         83.000000  
2                    155        124.000000  
3                    191         21.250000  
4                    129         10.000000  
...                  ...               ...  
27529                180         42.000000  
27530             

In [87]:
sub_feat = (submission.merge(ui_feat_31, how='left', on=['userID', 'itemID'])).merge(u_feat_31, how='left', on='userID')
sub_feat

userID  itemID  similar>0COrderSumIncl  similar>0COrderCountIncl  \
0          0   20664                       3                         3   
1          0   28231                       5                         4   
2         13    2690                       8                         6   
3         15    1299                       7                         7   
4         15   20968                      17                        15   
...      ...     ...                     ...                       ...   
9995   46118   20106                       6                         6   
9996   46124   19677                      13                        13   
9997   46125   12878                       3                         3   
9998   46127    7963                       8                         5   
9999   46130     395                      29                        19   

      similar>0COrderSumExcl  similar>0COrderCountExcl  sameBrandOrderSumIncl  \
0                          0                         0                      3   
1                          1                         1                      6   
2                          4                         2                      4   
3                          3                         3                      5   
4                         13                        11                      4   
...                      ...                       ...                    ...   
9995                       1                         1                      5   
9996                       7                         7                     12   
9997                       0                         0                      5   
9998                       0                         0                      8   
9999                      24                        16                      5   

      sameBrandOrderCountIncl  sameBrandOrderSumExcl  sameBrandOrderCountExcl  \
0                           3                      0                        0   
1                           4                      2                        1   
2                           4                      0                        0   
3                           5                      1                        1   
4                           4                      0                        0   
...                       ...                    ...                      ...   
9995                        5                      0                        0   
9996                       12                      6                        6   
9997                        5                      2                        2   
9998                        5                      0                        0   
9999                        3                      0                        0   

      ...  day_first_purchase  day_last_purchase  usage_time_items  \
0     ...                   4                193                94   
1     ...                 172                238                33   
2     ...                   5                206                67   
3     ...                 100                227                42   
4     ...                 129                238                36   
...   ...                 ...                ...               ...   
9995  ...                  36                205                42   
9996  ...                  68                236                33   
9997  ...                   3                244               120   
9998  ...                  36                196                25   
9999  ...                   2                202                89   

      u_avg_orders  u_avg_period  u_first_bought  u_last_bought  \
0             2.00         26.00               5            239   
1             2.00         26.00               5            239   
2             5.58         21.64               6            244   
3             4.43         16.62              23            23

In [88]:
sub_feat.isnull().any()


userID                      False
itemID                      False
similar>0COrderSumIncl      False
similar>0COrderCountIncl    False
similar>0COrderSumExcl      False
similar>0COrderCountExcl    False
sameBrandOrderSumIncl       False
sameBrandOrderCountIncl     False
sameBrandOrderSumExcl       False
sameBrandOrderCountExcl     False
cumsum                      False
avg_time_orders             False
day_first_purchase          False
day_last_purchase           False
usage_time_items            False
u_avg_orders                False
u_avg_period                False
u_first_bought              False
u_last_bought               False
u_std_avg_period            False
u_mean_bought               False
u_std_bought                False
dtype: bool

In [89]:
submission['prediction_23372'] = clf.predict(sub_feat)

In [94]:
submission['prediction_ranfor_23372'] = submission.apply(lambda row: int(row['prediction_23372']), axis=1)
sub_df = submission.drop('prediction_23372', axis=1)
sub_df

userID  itemID  prediction_ranfor_23372
0          0   20664                        0
1          0   28231                        0
2         13    2690                        0
3         15    1299                        0
4         15   20968                        0
...      ...     ...                      ...
9995   46118   20106                        0
9996   46124   19677                        0
9997   46125   12878                        0
9998   46127    7963                        0
9999   46130     395                        0

[10000 rows x 3 columns]

In [95]:
sub_df.prediction_ranfor_23372.value_counts()

0    9989
2       5
4       4
1       1
3       1
Name: prediction_ranfor_23372, dtype: int64

In [98]:
ui_sub = pd.read_csv('UI_submission_predictions.csv', sep='|', index_col=0)
ui_sub

userID  itemID  prediction
0          0   20664         0.0
1          0   28231         0.0
2         13    2690         0.0
3         15    1299         0.0
4         15   20968         0.0
...      ...     ...         ...
9995   46118   20106         3.0
9996   46124   19677         0.0
9997   46125   12878         0.0
9998   46127    7963         0.0
9999   46130     395         0.0

[10000 rows x 3 columns]

In [99]:
ui_sub.prediction.value_counts()

0.0    9243
4.0     287
3.0     248
1.0     131
2.0      91
Name: prediction, dtype: int64